# Generated by Django 2.2.17 on 2021-01-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
    ]
